Feat/#1 회원가입 기능 구현
Leets-Official/EatMate-BE pull request #2
Opened 2024-12-27 18:57 UTC by seokjun01

## 개요

- #1 회원가입 기능구현 (미완성)

-도메인 관련 부분

멤버 엔티티는  초반 Auth  로그인 성공 시 ,  DB에 저장하기 위해   추출 가능한 정보 이외에는 기본 값이 들어가게끔 (Null 허용 가능) 구현하였습니다. 
이는 사용자가 회원가입 페이지에서 프로필 관련 정보를 작성 시 , DB에 기본값 -> 사용자 작성 값으로 업데이트 되는 로직입니다.

사용자의 생년월일 같은 경우 클래스를 하나 만들어서 그 안의 필드에 출생년도, 월 , 일을 구분하였습니다.

성별(GENDER)과 ROLE(권한)은 enum으로 구현하였으며, 권한 같은 경우 소셜 로그인 특성 상 최초 로그인 시 회원가입 페이지로 리다이렉팅 하기 위해 GUEST 등급을 추가하여 구분하였습니다.

Dto는 현재, 회원가입 시 필요한 필드 위주로 구성하였고 이 필드에 저장된 값으로 DB의 기본값에서 업데이트 될 예정입니다.

-OAuth 소셜 로그인 부분

OAuth기반 구글 로그인 과정 설명
![image](https://github.com/user-attachments/assets/359944e3-7960-4c71-aa3b-59dd76c26800)

위 방식으로 로그인이 진행 되고, 서버 측에서 Access Token이 발급 됨을 확인할 수 있었습니다
<img width="1440" alt="스크린샷 2024-12-27 오전 4 28 05" src="https://github.com/user-attachments/assets/a23d50da-d764-442b-9fa5-0f1cbd4fd4d7" />
<img width="1284" alt="스크린샷 2024-12-28 오전 2 34 01" src="https://github.com/user-attachments/assets/65a21e44-c130-4a6d-a954-7d73c7953f08" />

추후 개발 과제는, OAuth2LoginSuccessHandler 코드에서

구글 로그인 성공시,
최초 로그인(회원 등록이 안된)인 사용자가 리다이렉트 되는 URL(회원 프로필을 작성 및 등록하는 페이지)과 
그렇지 않은(회원 가입을 이미 한)  사용자가 리다이렉트 되는 URL (아마 메인 페이지)를 설정하여서 실제 DB에 업데이트 되는지 확인이 필요합니다.

백엔드 측에서 뷰를 랜더링해서 해보려 했으나, favicon 에러가 발생하여서 추후 프론트와 논의 후 개발하겠습니다.

구조/설계적인 피드백이나 더 좋은 방법, 있으면 코멘트 부탁드립니다

 

## PR 유형
어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

📣 **To Reviewers**
---

2024-12-28 03:47 UTC, jj0526 requested changes
구현하느라 수고 많으셨어요! 코드 리뷰하면서 많이 배웠습니다

2024-12-28 03:47 UTC, jj0526 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +    private String mbti;
mbti도 enum으로 해주시면 좋을거같아요!

2024-12-28 03:47 UTC, jj0526 commented on src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("User not found with email: " + signUpRequestDto.getEmail()));
만드신 커스텀 예외를 사용하시는게 좋아보입니다!

2024-12-28 03:47 UTC, jj0526 commented on src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
> +                        () -> new Exception("일치하는 회원이 없습니다.")
여기도 커스텀 예외로 처리해주시면 될거같아요!

2024-12-28 03:47 UTC, jj0526 commented on src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthAttributes.java
> +        return new OAuthAttributes(nameAttributeKey, googleOAuthUserInfo);
이부분은 빌더로 한번에 처리할 수 있을거같아요!!

2024-12-28 03:47 UTC, jj0526 commented on src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthAttributes.java
> +                .studentNumber("default_student") // 기본 학번 설정
기본 설정은 상수처리 하는게 어떨까요?

2024-12-28 05:23 UTC, ehs208 requested changes
어려운 부분 구현하시느라 고생 많으셨습니다!

PR올리실 때, Label에 종류는 한가지만 골라주시면 될 것 같습니다.
또 본인 이름으로 된 Label 생성해 두었는데 같이 선택해주시면 감사드릴게요!

추가로 리뷰어 선택시 Team 단위로 한번에 선택해서 태그해주시면 편하게 태그 가능합니다.

2024-12-28 05:23 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +    private String studentNumber;
학번은 `Long` 타입으로 받는게 좋아 보입니다!

2024-12-28 05:23 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Gender.java
> +        return genderType;
`@Getter` 와 `@NoArgsConstructor` 어노테이션 사용도 가능할 것 같습니다!

2024-12-28 05:23 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +@Builder
`@AllArgsConstructor` 사용은 지양하는게 좋을 것 같습니다! 
`@Builder` 어노테이션 또한 생성자 위에 위치해주시는게 좋다 생각됩니다!

하단 블로그 글 읽어보시면 좋을거 같습니다

[@RequiredArgsConstructor, @AllArgsConstructor 사용은 지양하자!](https://velog.io/@joona95/RequiredArgsConstructor-AllArgsConstructor-%EC%82%AC%EC%9A%A9%EC%9D%80-%EC%A7%80%EC%96%91%ED%95%98%EC%9E%90)

2024-12-28 05:23 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Role.java
> +    }
여기도 마찬가지로 @Getter 와 @NoArgsConstructor 어노테이션 사용 가능 할 것 같습니다!

2024-12-28 05:23 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/exception/MemberAlreadyExistsException.java
> +public class MemberAlreadyExistsException extends RuntimeException {
이 부분은 커스텀 에러이기 때문에 `RuntimeException`보다 `CommonException` 을 상속하는게 맞다고 생각됩니다!
또 노션에 예외처리 관련 컨벤션 한번 확인해주시면 감사드리겠습니다!

2024-12-28 05:23 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
> +            throw new MemberAlreadyExistsException(ErrorCode.MEMBER_ALREADY_EXISTS);
이 부분도 노션 확인 해보시고 변경 부탁드려요!

2024-12-28 05:23 UTC, ehs208 commented on src/main/java/com/example/eatmate/global/auth/login/controller/AuthController.java
> +    @PostMapping("/register")
회원가입은 OAuth2 사용하는데, 유효한 메소드일까요?!

2024-12-28 05:23 UTC, ehs208 commented on src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
> +
아래 회원 주석 아래로 내려주시는게 좋을 것 같습니다.

2024-12-28 09:08 UTC, dyk-im reviewed
OAuth2를 활용한 구글 소셜 로그인 및 회원가입 기능 구현하시느라 고생하셨습니다! 코드 정독하며 알게된 부분도 있고 제가 아는 선과 추가적으로 찾아본 내용을 바탕으로 몇 가지 궁금한 점과 수정했으면 하는 부분에 대해 리뷰 달았습니다! 읽어보시고 의견 공유해주시면 좋을 것 같아요!

https://velog.io/@codesusuzz/Spring-Boot-JWT-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-3-JWT-%EB%B0%9C%EA%B8%89
찾아보면서 위의 자료도 좀 참고했는데 이미 활용하셨을 수도 있지만 정리가 간단하게 정리가 되어있는 것 같아 추가 첨부 해봅니다!

2024-12-28 09:08 UTC, dyk-im commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +public class Member {
가능하다면 BaseTime Entity도 추가해주시면 좋을 것 같습니다!
컨벤션을 따른 공유디렉터리에 클래스 생성하고, application.java에 어노테이션 추가하시면 될 것 같아요!

2024-12-28 09:08 UTC, dyk-im commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +@NoArgsConstructor
엔티티에서 기본 생성자의 경우 JPA의 지연로딩으로 인해 프록시에서 생성하게 됩니다. 이때 무분별한 생성을 막기위해 제한 조건을 걸 필요가 있습니다. 고로 @NoArgsConstructor(access = AccessLevel.PROTECTED) 로 명시해주는 것이 좋을 것 같습니다!

2024-12-28 09:08 UTC, dyk-im commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +    private BirthDate birthDate;   // yyyy-mm-dd 형식으로 받아야함
임베디드 타입 객체로 @Embedded 어노테이션이 필요합니다!

2024-12-28 09:08 UTC, dyk-im commented on src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginSuccessHandler.java
> +            response.addHeader(jwtService.getRefreshHeader(), "Bearer " + refreshToken);
Token 전달 방식
현재는 헤더에 토큰을 담아 응답하는 방식입니다. 보편적인 방법이지만, 더 안전한 전달 방식으로 HTTP-Only 쿠키를 고려할 수 있습니다:
HTTP-Only 쿠키를 사용하면 클라이언트의 스크립트로부터 토큰이 노출되지 않습니다.
Access Token은 헤더로 보내고, Refresh Token만 쿠키에 저장하는 혼합 방식도 가능합니다.
=> 위와 같은 방식도 추후 고려해보면 좋을 것 같습니다! Refresh Token 을 전달하는 더 안전한 방법이 될 수 있을 것 같습니다!
또한 Refresh Token의 저장매체에 대해서도 여러 방법이 있으니 다양하게 생각해보면 좋을 것 같습니다!

2024-12-28 09:08 UTC, dyk-im commented on src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginSuccessHandler.java
> +                response.sendRedirect("/"); // 프론트의 회원가입 추가 정보 입력 폼으로 리다이렉트
경로를 추후 잘 맞춰야할 것 같습니다!

2024-12-28 09:08 UTC, dyk-im commented on src/main/java/com/example/eatmate/global/config/SecurityConfig.java
> +					.requestMatchers("/sign-up").permitAll() // 회원가입 접근 가능
스웨거 부분은 석준님 파트는 아니지만 기록을 위해 작성하겠습니다! 추후 아래의 예시와 같이 스웨과 관련 api와 로그인 api가 추가될 필요가 있다고 생각합니다! 그리고 h2console 코드는 테스트를 위해 넣은 것인지 궁금합니다!
.requestMatchers("/v3/api-docs", "/v3/api-docs/**", "/swagger-ui.html", "/swagger-ui/**", "/swagger/**").permitAll()
.requestMatchers("/api/users/login").permitAll()

2024-12-29 07:21 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("User not found with email: " + signUpRequestDto.getEmail()));
빠뜨린 부분인데 지적감사드립니다! 수정하겠습니다!

2024-12-29 07:21 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +    private String mbti;
enum타입으로 생성 완료하였습니다!

2024-12-29 07:24 UTC, seokjun01 commented on src/main/java/com/example/eatmate/global/auth/jwt/JwtService.java
> +                        () -> new Exception("일치하는 회원이 없습니다.")
수정 완료입니다!

2024-12-29 07:31 UTC, seokjun01 commented on src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthAttributes.java
> +        return new OAuthAttributes(nameAttributeKey, googleOAuthUserInfo);
빌더로 수정하니 기존의 코드 보다 보기좋고, 확장 유연성에 좋은 것 같습니다
좋은 피드백 감사합니다

2024-12-29 07:34 UTC, seokjun01 commented on src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthAttributes.java
> +                .studentNumber("default_student") // 기본 학번 설정
수정완료입니다!

2024-12-29 07:39 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Gender.java
> +        return genderType;
Getter 어노테이션 추가했습니다!

@NoArgsConstructor 어노테이션 같은 경우는 enum 타입이 미리 정의된 값을 사용하기 때문에 기본 생성자는 불필요하다고 생각되는데 혹시 다른 이유가 있으신지 여쭤봐도 될까요?!

2024-12-29 07:39 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +    private String studentNumber;
넵! 수정하겠습니다

2024-12-29 07:57 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +@Builder
참고 블로그 글 잘 읽었습니다! 
필드 순서에 의한 의존성 문제가 발생될 수 있음을 알게되었습니다! 수정해놓겠습니다

2024-12-29 07:58 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Role.java
> +    }
수정 완료하였습니다!

2024-12-29 08:01 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/exception/MemberAlreadyExistsException.java
> +public class MemberAlreadyExistsException extends RuntimeException {
예외처리 컨벤션 확인해보겠습니다. 
커스텀 에러에 맞게 상속 예외를 변경하였고, 
디렉토리 구조가 복잡해지는 것 같아서 custom 디렉토리로 예외를 옮겼습니다.

2024-12-29 08:06 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +    private BirthDate birthDate;   // yyyy-mm-dd 형식으로 받아야함
refreshToken, birthdate 둘 다 말씀하시는걸까요?

2024-12-29 08:07 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
> +            throw new MemberAlreadyExistsException(ErrorCode.MEMBER_ALREADY_EXISTS);
우선 변경 완료 하였는데, 이런 방식으로 하는게 맞는지 재검토 부탁드립니다

2024-12-29 08:08 UTC, seokjun01 commented on src/main/java/com/example/eatmate/global/config/error/ErrorCode.java
> +
수정 완료했습니다!

2024-12-29 08:11 UTC, seokjun01 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Member.java
> +@NoArgsConstructor
좋은 피드백 감사합니다. 수정 완료하였습니다

2024-12-29 08:12 UTC, seokjun01 commented on src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthLoginSuccessHandler.java
> +            response.addHeader(jwtService.getRefreshHeader(), "Bearer " + refreshToken);
조금 더 보안이 강화된다는 점에서 장점이 있는 방법인 것 같습니다! 개발 후 보안 강화시에 적용해봐도 좋은 방법인거 같습니다. 좋은 피드백 감사합니다.

2024-12-29 09:09 UTC, dyk-im commented on src/main/java/com/example/eatmate/global/common/BaseTimeEntity.java
> +mport jakarta.persistence.EntityListeners;
이 부분 제거부탁드릴게용 

그리고 
```
@Getter
@EntityListeners(AuditingEntityListener.class)
@MappedSuperclass
public class BaseTimeEntity {
	@CreatedDate
	@Column(updatable = false)
	private LocalDateTime createdAt;

	@LastModifiedDate
	@Column
	private LocalDateTime updatedAt;

	public LocalDateTime getCreatedAt() {
		return createdAt.atZone(ZoneId.of("Asia/Seoul")).toLocalDateTime();
	}

	public LocalDateTime getUpdatedAt() {
		return updatedAt.atZone(ZoneId.of("Asia/Seoul")).toLocalDateTime();
	}
}
```
위의 코드처럼 수정하고 member에서 extends BaseTimeEntity를 하시면 db에 컬럼으로 추가되어 확인하실 수 있습니다!

2024-12-29 09:09 UTC, dyk-im commented on src/main/java/com/example/eatmate/global/config/SecurityConfig.java
> +					.requestMatchers("/sign-up").permitAll() // 회원가입 접근 가능
수정해주신 부분 확인했습니다! 그중 .requestMatchers("/api/users/login").permitAll() 이 코드는 저희와 관련없는 코드라 제거해주시면 감사하겠습니다!

2024-12-29 09:11 UTC, dyk-im commented on src/main/java/com/example/eatmate/global/common/BaseTimeEntity.java
> +mport jakarta.persistence.EntityListeners;
위에 import문 제거하시면 ci 작업 통과할 것 같습니다!

2024-12-29 18:55 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/domain/Gender.java
> +        return genderType;
제가 착각했습니다! `@NoArgsConstructor` 는 없어도 될거 같습니다!

2024-12-29 19:06 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/service/MemberService.java
> +            throw new MemberAlreadyExistsException(ErrorCode.MEMBER_ALREADY_EXISTS);
```
throw new CommonException(ErrorCode.MEMBER_ALREADY_EXISTS);
```
이렇게 처리하는게 제가 의도한 바였습니다. 또한 원하시는 방법대로 하시려면 
```
throw new MemberAlreadyExistsException
```
이렇게만 하셔도 될 것 같습니다.

두가지 방법 모두 사용 가능하지만 제가 생각하기엔 `ErrorCode`에 이미 에러의 종류와 메시지를 모두 정의하고 있는데, 다시 커스텀 예외 클래스를 만드는 것은 중복이고, ErrorCode만으로도 어떤 예외상황인지 충분히 표현된다고 생각되어 제가 노션에 적어둔 방법을 권해드렸습니다.

이 부분은 컨벤션이기 때문에 우선 제가 말씀드린대로 변경해주시고 추후 회의때 한번 다시 이야기 해보면 좋을 것 같습니다.

2024-12-29 19:07 UTC, ehs208 commented on src/main/java/com/example/eatmate/app/domain/member/exception/MemberAlreadyExistsException.java
> +public class MemberAlreadyExistsException extends RuntimeException {
아래애 적어놨지만 말씀해주신대로 디렉토리가 복잡해져 이 파일 자체를 생성하지 않는 방법으로 컨벤션을 정했습니다.,,!

2024-12-30 06:08 UTC, jj0526 commented on src/main/java/com/example/eatmate/global/auth/login/oauth/OAuthAttributes.java
> +                .studentNumber("default_student") // 기본 학번 설정
넵!! 수고 많으셨어요

2024-12-30 06:20 UTC, seokjun01 commented on src/main/java/com/example/eatmate/global/config/SecurityConfig.java
> +					.requestMatchers("/sign-up").permitAll() // 회원가입 접근 가능
네 수정하였습니다

2024-12-30 12:41 UTC, seokjun01 commented on src/main/java/com/example/eatmate/global/common/BaseTimeEntity.java
> +mport jakarta.persistence.EntityListeners;
수정 완료하였습니다!

2024-12-30 12:51 UTC, dyk-im approved these changes
코드 확인 잘 했습니다! 고생하셨습니다!!

2024-12-30 12:54 UTC, ehs208 approved these changes
고생하셨습니다 !

2024-12-30 13:18 UTC, jj0526 approved these changes
수고하셨습니다!!

2024-12-30 15:13 UTC, merged